## Exercício 1.1 - Criando Arrays com Diferentes Métodos
- Crie os seguintes arrays usando NumPy:

- Um array 1D com os valores [10, 20, 30, 40, 50] usando np.array()
- Um array com valores de 0 a 9 usando np.arange()
- Um array com 5 zeros usando np.zeros()
- Um array 2D com 3 linhas e 4 colunas preenchido com uns usando np.ones()
- Exiba cada array criado.


In [29]:
import numpy as np
print(np.array([10, 20, 30, 40, 50]))
print(np.arange(10))
print(np.zeros(5))
print(np.ones((3,4)))

[10 20 30 40 50]
[0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## Exercício 2 - Explorando Atributos de Arrays
 Crie um array 2D com shape (3, 4) usando np.arange(12).reshape(3, 4) e então:

- Exiba o array
- Verifique e exiba o shape do array
- Verifique e exiba o dtype do array
- Verifique e exiba o size do array
- Verifique e exiba o ndim (número de dimensões) do array

In [30]:
array2d = np.arange(12).reshape(3,4)
print(array2d.shape)
print(array2d.dtype)
print(array2d.size)
print(array2d.ndim)



(3, 4)
int64
12
2


# Exercício 3 - Conversão de Tipos e Arrays Multidimensionais
Crie um array 3D com shape (2, 3, 4) preenchido com números de ponto flutuante entre 0 e 1 usando np.random.rand(2, 3, 4). Em seguida:

- Exiba o array original e seu dtype
- Converta o array para inteiro usando .astype(int) (os valores serão truncados)
- Multiplique o array original por 100 e depois converta para inteiro
- Verifique o shape de cada array criado
- Crie um array de zeros com o mesmo shape mas dtype float64

In [31]:
array3d = np.random.rand(2,3,4)
print(array3d.dtype)
# print(array3d.astype(int))
array3d *= 100
print(array3d.astype(int))
print(array3d.shape)

array_zeros = np.zeros((2,3,4), dtype=int)
print(array_zeros)

float64
[[[80 19 64 13]
  [95 63  0 86]
  [27  2 15 92]]

 [[ 8 97 51 87]
  [16 38 54 85]
  [82  2 33  9]]]
(2, 3, 4)
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


# Exercício 4 - Operações Elemento a Elemento
Dados os arrays:

- arr1 = np.array([10, 20, 30, 40])
- arr2 = np.array([2, 3, 4, 5])
#
 Realize as seguintes operações e exiba os resultados:

- Soma: arr1 + arr2
- Subtração: arr1 - arr2
- Multiplicação elemento a elemento: arr1 * arr2
- Divisão elemento a elemento: arr1 / arr2
- Potência: arr1 ** 2 (arr1 ao quadrado)

In [32]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([2, 3, 4, 5])

print(f"Soma: {arr1 + arr2}")
print(f"Subtração: {arr1 - arr2}")
print(f"Multiplicação: {arr1 * arr2}")
print(f"Divisão: {arr1 / arr2}")
print(f"Potência: {arr1 ** 2}")

Soma: [12 23 34 45]
Subtração: [ 8 17 26 35]
Multiplicação: [ 20  60 120 200]
Divisão: [5.         6.66666667 7.5        8.        ]
Potência: [ 100  400  900 1600]


# Exercício 5 - Reshape Básico
Dado o array arr = np.arange(12) (valores de 0 a 11):

- Remodele o array para uma matriz 3x4 usando .reshape(3, 4)
- Remodele o array para uma matriz 4x3
- Remodele o array para uma matriz 2x6
- Remodele o array para uma matriz 6x2
#
Use -1 para que o NumPy calcule automaticamente uma dimensão: .reshape(2, -1) 
#
Exiba cada resultado e verifique o shape de cada matriz criada.

In [33]:
arr = np.arange(12)

reshape1 = arr.reshape(3,4)
reshape2 = arr.reshape(4,3)
reshape3 = arr.reshape(2,6)
reshape4 = arr.reshape(6,2)
reshape5 = arr.reshape(2,-1)

print(f'===Exibição===\n'
      f'Array 1: {reshape1}\n'
      f'Array 2:{reshape2}\n'
      f'Array 3:{reshape3}\n'
      f'Array 4:{reshape4}\n'
      f'Array 5: {reshape5}')

===Exibição===
Array 1: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Array 2:[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Array 3:[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
Array 4:[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
Array 5: [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


# Pandas

# Exercício 6 - Criando e Acessando DataFrames
Crie um DataFrame chamado funcionarios a partir do dicionário:

{
    'Nome': ['Ana', 'Bruno', 'Carla', 'Diego'],
    'Idade': [28, 32, 25, 30],
    'Cargo': ['Analista', 'Gerente', 'Desenvolvedor', 'Analista']
}
# 
Em seguida:

- Exiba o DataFrame completo
- Exiba o tipo do DataFrame usando type()
- Acesse a coluna 'Nome' usando notação de ponto (df.Nome)
- Acesse a coluna 'Idade' usando notação de colchetes (df['Idade'])
- Acesse a coluna 'Cargo' usando ambas as notações
- Exiba apenas as colunas 'Nome' e 'Cargo' usando colchetes com lista
- Saída esperada (exemplos):
#
 -   Nome     Idade        Cargo
- 0         Ana     28     Analista
- 1  Bruno     32     Gerente
- 2  Carla     25  Desenvolvedor
- 3  Diego     30     Analista

In [34]:
import pandas as pd
dados = {
    'Nome': ['Ana', 'Bruno', 'Carla', 'Diego'],
    'Idade': [28, 32, 25, 30],
    'Cargo': ['Analista', 'Gerente', 'Desenvolvedor', 'Analista']
}

df = pd.DataFrame(dados)
display(df)
print(type(df))

coluna_nome = df.Nome
coluna_idade = df['Idade']
# print(df['Cargo'])
print(df[['Nome', 'Cargo']])
# print(coluna_nome)
# print(coluna_idade)



,Nome,Idade,Cargo
0,Ana,28,Analista
1,Bruno,32,Gerente
2,Carla,25,Desenvolvedor
3,Diego,30,Analista


<class 'pandas.DataFrame'>
    Nome          Cargo
0    Ana       Analista
1  Bruno        Gerente
2  Carla  Desenvolvedor
3  Diego       Analista


# Exercício 7 - Lendo um Arquivo CSV
Leia o arquivo CSV disponível em: https://raw.githubusercontent.com/plotly/datasets/master/gapminderDataFiveYear.csv
- Armazene os dados em um DataFrame chamado df_mundo
- Exiba as primeiras 5 linhas usando .head()
- Exiba as últimas 3 linhas usando .tail()
- Verifique o número de linhas e colunas usando .shape
- Exiba os nomes das colunas usando .columns


In [35]:
df_mundo = pd.read_csv(r'arquivo.csv') 

# display(df_mundo[:5])
display(df_mundo.head())

# display(df_mundo[-3:])
display(df_mundo.tail(3))


,country,year,pop,continent,lifeExp,gdpPercap
0,Afghanistan,1952,8425333.0,Asia,28.801,779.445314
1,Afghanistan,1957,9240934.0,Asia,30.332,820.853030
2,Afghanistan,1962,10267083.0,Asia,31.997,853.100710
3,Afghanistan,1967,11537966.0,Asia,34.020,836.197138
4,Afghanistan,1972,13079460.0,Asia,36.088,739.981106


,country,year,pop,continent,lifeExp,gdpPercap
1701,Zimbabwe,1997,11404948.0,Africa,46.809,792.449960
1702,Zimbabwe,2002,11926563.0,Africa,39.989,672.038623
1703,Zimbabwe,2007,12311143.0,Africa,43.487,469.709298


In [36]:
print(df.shape)
print(df.columns)

(4, 3)
Index(['Nome', 'Idade', 'Cargo'], dtype='str')


# Exercício 8 - Análise Exploratória de Dados
Leia o arquivo CSV: https://raw.githubusercontent.com/plotly/datasets/master/gapminderDataFiveYear.csv e armazene em df_exploracao.

Realize uma análise exploratória completa:

- Exiba as primeiras 10 linhas
- Verifique as dimensões e tipos de dados
- Identifique quantos países únicos existem na coluna 'country'
- Identifique quantos anos únicos existem na coluna 'year'
- Verifique se há valores ausentes usando .isna().sum()
- Exiba estatísticas descritivas das colunas numéricas
- Identifique o país com maior população em todo o dataset
- Identifique o país com menor expectativa de vida

In [40]:
df_exploracao = pd.read_csv(r'arquivo.csv')

display(df_exploracao[:11])
print(f'Dimensões: {df_exploracao.shape} \n'
      f'Tipos de dados: {df_exploracao.dtypes}')

,country,year,pop,continent,lifeExp,gdpPercap
0,Afghanistan,1952,8425333.0,Asia,28.801,779.445314
1,Afghanistan,1957,9240934.0,Asia,30.332,820.853030
2,Afghanistan,1962,10267083.0,Asia,31.997,853.100710
3,Afghanistan,1967,11537966.0,Asia,34.020,836.197138
4,Afghanistan,1972,13079460.0,Asia,36.088,739.981106
5,Afghanistan,1977,14880372.0,Asia,38.438,786.113360
6,Afghanistan,1982,12881816.0,Asia,39.854,978.011439
7,Afghanistan,1987,13867957.0,Asia,40.822,852.395945
8,Afghanistan,1992,16317921.0,Asia,41.674,649.341395
9,Afghanistan,1997,22227415.0,Asia,41.763,635.341351


Dimensões: (1704, 6) 
Tipos de dados: country          str
year           int64
pop          float64
continent        str
lifeExp      float64
gdpPercap    float64
dtype: object


In [46]:
# Quantos países únicos existem na coluna 'country'?
coluna_country = df_exploracao['country']
print(f'Valores distintos contry: {coluna_country.nunique()}')

# Quantos anos únicos existem na coluna 'year'?
coluna_year = df_exploracao['year']
print(f'Valores distintos year: {coluna_year.nunique()}')

# valores ausentes
print(df_exploracao.isna().sum())

# Exiba estatísticas descritivas das colunas numéricas
display(df_exploracao.describe())

Valores distintos contry: 142
Valores distintos year: 12
country      0
year         0
pop          0
continent    0
lifeExp      0
gdpPercap    0
dtype: int64


,year,pop,lifeExp,gdpPercap
count,1704.00000,1.704000e+03,1704.000000,1704.000000
mean,1979.50000,2.960121e+07,59.474439,7215.327081
std,17.26533,1.061579e+08,12.917107,9857.454543
min,1952.00000,6.001100e+04,23.599000,241.165876
25%,1965.75000,2.793664e+06,48.198000,1202.060309
50%,1979.50000,7.023596e+06,60.712500,3531.846988
75%,1993.25000,1.958522e+07,70.845500,9325.462346
max,2007.00000,1.318683e+09,82.603000,113523.132900


In [57]:
# Qual o país com maior população em todo o dataset?
filtro_maior = coluna_country.max()
indMax = df_exploracao.loc[['population'].idmax()]
print(f'País com maior população é {filtro_maior} com {filtro_maior}')

# Qual o país com menor expectativa de vida?
filtro_menor = df_exploracao['lifeExp'].min()
print(f'O país com menor expectativa de vida é o {filtro_menor['country']} com {filtro_menor['lifeExp']}')

AttributeError: 'list' object has no attribute 'idmax'